expensify/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('reports', include('reports.urls')),
    path('admin/', admin.site.urls),
]

reports/urls.py
from django.urls import path

from . import views

app_name = 'reports'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('/add_expense', views.AddExpenseView.as_view(), name='add_expense'),
    path('/add_income', views.AddIncomeView, name='add_income'),
    path('/submit_expense', views.submit_expense, name='submit_expense'),
    path('/submit_income', views.submit_income, name='submit_income'),
    path('/submit_edited_expense', views.submit_edited_expense, name='submit_edited_expense'),
    path('/submit_edited_income', views.submit_edited_income, name='submit_edited_income'),
    path('/<int:expense_id>/delete_expense', views.delete_expense, name='delete_expense'),
    path('/<int:income_id>/delete_income', views.delete_income, name='delete_income'),
    path('/<int:expense_id>/edit_expense', views.edit_expense, name='edit_expense'),
    path('/<int:income_id>/edit_income', views.edit_income, name='edit_income'),
    # path('/expense_pie.png', views.expense_pie, name='expense_pie'),
    path('/add_category', views.add_category, name='add_category'),
    path('/submit_new_category', views.submit_new_category, name='submit_new_category'),
]

reports/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=50)
    
    def __str__(self):
        return self.name


class Expense(models.Model):
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    date_paid = models.DateField()
    
    def __str__(self):
        return self.name


class Income(models.Model):
    amount = models.DecimalField(max_digits=11, decimal_places=2)
    name = models.CharField(max_length=50)
    date_paid = models.DateField()
    
    def __str__(self):
        return self.name

reports/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.views import generic

import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas

import datetime

from dateutil.relativedelta import relativedelta

from decimal import Decimal

from .models import Expense, Category, Income


class IndexView(generic.ListView):
    template_name = 'reports/index.html'
    context_object_name = 'money_list'
    
    expenses = Expense.objects.all()
    
    for expense in expenses:
        if expense.date_paid.month != datetime.datetime.now().month:
            diff = datetime.datetime.now().month - expense.date_paid.month
            expense.date_paid = expense.date_paid + relativedelta(months=diff)
            expense.save()
            
    if expenses:
        labels = []
        for expense in expenses:
            if expense.category.name not in labels:
                labels.append(expense.category.name)
        sizes = [0.0] * len(labels)
        for expense in expenses:
            for i in range(len(labels)):
                if expense.category.name == labels[i]:
                    sizes[i] += 1
        fig1, ax1 = plt.subplots()
        total_cat = sum(sizes)
        for i in range(len(sizes)):
            sizes[i] = (sizes[i] / total_cat) * 100
        ax1.pie(sizes, labels=labels, autopct='%1.1f%%')
        ax1.axis('equal')
        fig1.savefig('reports/static/reports/img/cat_breakdown.png')
            
    def get_queryset(self):
        """
        Return all expenses and income, order by name
        """
        expenses = Expense.objects.order_by('-name')
        incomes = Income.objects.order_by('-name')
        total = 0
        for income in incomes:
            total += income.amount
        for expense in expenses:
            total -= expense.amount
        money_list = [expenses, incomes, total]
        return money_list


class AddExpenseView(generic.ListView):
    template_name = 'reports/add_expense.html'
    context_object_name = 'new_expense_list'
    
    def get_queryset(self):
        """
        Return all expenses, order by name
        """
        return Category.objects.all()


def AddIncomeView(request):
    return render(request, 'reports/add_income.html')


def submit_expense(request):
    try:
        expense_name = request.POST['expenseName']
        amt = request.POST['expenseAmount']
        cat_id = request.POST['expenseCategory']
        date = datetime.datetime.strptime(request.POST['expenseDate'], "%Y-%m-%d")
        cat = Category.objects.get(id=int(cat_id))
    except (KeyError):
        return render(request, 'reports/add_expense.html', {
            'error_message': "You didn't enter all the information.",
            'new_expense_list': Category.objects.all(),
        })
    else:
        if expense_name == "" or amt == "":
            return render(request, 'reports/add_expense.html', {
                'error_message': "You didn't enter all the information.",
                'new_expense_list': Category.objects.all(),
            })
        if Expense.objects.filter(name=cat.name).exists():
            return render(request, 'reports/add_expense.html', {
                'error_message': "That expense already exists.",
                'new_expense_list': Category.objects.all(),
            })
        new_expense = Expense(category=cat, amount=Decimal(amt), name=expense_name, date_paid=date)
        new_expense.save()
        return HttpResponseRedirect(reverse('reports:index'))


def submit_edited_expense(request):
    try:
        expense_name = request.POST['expenseName']
        amt = request.POST['expenseAmount']
        cat_id = request.POST['expenseCategory']
        cat = Category.objects.get(id=int(cat_id))
        date = datetime.datetime.strptime(request.POST['expenseDate'], "%Y-%m-%d").date()
        exp_id = request.POST['expenseID']
        expense = Expense.objects.get(id=int(exp_id))
    except (KeyError):
        expense = Expense.objects.get(id=int(request.POST['expenseID']))
        expense_list = [Category.objects.all(), expense]
        return render(request, 'reports/edit_expense.html', {
            'error_message': "You didn't enter all the information.",
            'expense_list': expense_list,
        })
    else:
        if expense_name == "" or amt == "":
            expense_list = [Category.objects.all(), expense]
            return render(request, 'reports/edit_expense.html', {
                'error_message': "You didn't enter all the information.",
                'expense_list': expense_list,
            })
        expense.category = cat 
        expense.amount = Decimal(amt)
        expense.name = expense_name
        expense.date_paid = date
        print("new expense date: " + str(expense.date_paid))
        expense.save()
        return HttpResponseRedirect(reverse('reports:index'))


def submit_income(request):
    try:
        income_name = request.POST['incomeName']
        amt = request.POST['incomeAmount']
        date = datetime.datetime.strptime(request.POST['incomeDate'], "%Y-%m-%d")
    except (KeyError):
        return render(request, 'reports/add_income.html', {
            'error_message': "You didn't enter all the information.",
        })
    else:
        if income_name == "" or amt == "":
            return render(request, 'reports/add_income.html', {
                'error_message': "You didn't enter all the information.",
            })
        new_income = Income(amount=Decimal(amt), name=income_name, date_paid=date)
        new_income.save()
        return HttpResponseRedirect(reverse('reports:index'))


def submit_edited_income(request):
    try:
        income_name = request.POST['incomeName']
        amt = request.POST['incomeAmount']
        inc_id = request.POST['incomeID']
        income = Income.objects.get(id=int(inc_id))
        date = datetime.datetime.strptime(request.POST['incomeDate'], "%Y-%m-%d")
    except (KeyError):
        return render(request, 'reports/edit_income.html', {
            'error_message': "You didn't enter all the information.",
            'income': income,
        })
    else:
        if income_name == "" or amt == "":
            return render(request, 'reports/edit_income.html', {
                'error_message': "You didn't enter all the information.",
                'income': income,
            })
        income.amount = Decimal(amt)
        income.name = income_name
        income.date_paid = date
        income.save()
        return HttpResponseRedirect(reverse('reports:index'))


def delete_expense(request, expense_id):
    expense = get_object_or_404(Expense, pk=expense_id)
    expense.delete()
    return HttpResponseRedirect(reverse('reports:index'))


def delete_income(request, income_id):
    income = get_object_or_404(Income, pk=income_id)
    income.delete()
    return HttpResponseRedirect(reverse('reports:index'))


def edit_expense(request, expense_id):
    expense_list = [Category.objects.all(), Expense.objects.get(id=expense_id)]    
    return render(request, 'reports/edit_expense.html', {'expense_list': expense_list})


def edit_income(request, income_id):
    return render(request, 'reports/edit_income.html', {'income': Income.objects.get(id=income_id)})
    
# https://stackoverflow.com/questions/45460145/how-to-render-a-matplotlib-plot-in-a-django-web-application
"""
def expense_pie(expenses):
    # expenses = Expense.objects.all()
    labels = []
    for expense in expenses:
        if expense.category.name not in labels:
            labels.append(expense.category.name)
    sizes = [0.0] * len(labels)
    for expense in expenses:
        for i in range(len(labels)):
            if expense.category.name == labels[i]:
                sizes[i] += 1
    fig1, ax1 = plt.subplots()
    total_cat = sum(sizes)
    for i in range(len(sizes)):
        sizes[i] = (sizes[i] / total_cat) * 100
    ax1.pie(sizes, labels=labels, autopct='%1.1f%%')
    ax1.axis('equal')
    fig1.savefig('reports/static/reports/img/cat_breakdown.png')
    canvas = FigureCanvas(fig1)
    response = HttpResponse(content_type='image/jpg')
    canvas.print_jpg(response)
    return response
"""


def add_category(request):
    return render(request, 'reports/add_category.html')    


def submit_new_category(request):
    try:
        cat_name = request.POST['categoryName']
    except (KeyError):
        return render(request, 'reports/add_category.html', {
            'error_message': "You didn't enter all the information.",
        })
    else:
        if cat_name == "":
            return render(request, 'reports/add_category.html', {
                'error_message': "You didn't enter all the information.",
            })
        if Category.objects.filter(name=cat_name).exists():
            return render(request, 'reports/add_category.html', {
                'error_message': "That category already exists.",
            })
        new_category = Category(name=cat_name)
        new_category.save()
        return HttpResponseRedirect(reverse('reports:index'))

reports/templates/reports/add_category.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'reports:submit_new_category' %}" method="post">
        {% csrf_token %}
        <label for="catName">Name of Category (Entertainment, Gas, Food, etc.): </label>
        <input type="text" name="categoryName" id="catName" required><br>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

reports/templates/reports/add_expense.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'reports:submit_expense' %}" method="post">
        {% csrf_token %}
        <label for="expName">Name of expense (Netflix, Hulu, etc.): </label>
        <input type="text" name="expenseName" id="expName"><br>
        <label for"expAmt">Amount: </label>
        <input type="number" name="expenseAmount" id="expAmt" min=1 step="any"><br>
        <label for="expCat">Expense category: </label>
        <select name="expenseCategory" id="expCat">
            {% for cat in new_expense_list %}
                <option value="{{ cat.id }}">{{ cat.name }}</option>
            {% endfor %}
        </select><br>
        <label for="expDate">Date paid: </label>
        <input type="date" name="expenseDate" id="expDate"><br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

reports/templates/reports/add_income.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'reports:submit_income' %}" method="post">
        {% csrf_token %}
        <label for="incName">Name of income (Paycheck, Disablity, Stocks, etc.): </label>
        <input type="text" name="incomeName" id="incName" required><br>
        <label for="incAmt">Amount: </label>
        <input type="number" name="incomeAmount" id="incAmt" min=1 step="any" required><br>
        <label for="incDate">Date paid: </label>
        <input type="date" name="incomeDate" id="incDate" required><br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

reports/templates/reports/edit_expense.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'reports:submit_edited_expense' %}" method="post">
        {% csrf_token %}
        <label for="expName">Name of expense (Netflix, Hulu, etc.): </label>
        <input type="text" name="expenseName" id="expName" value="{{ expense_list.1.name }}" required><br>
        <label for="expAmt">Amount: </label>
        <input type="number" name="expenseAmount" id="expAmt" min=1 step="any" value="{{ expense_list.1.amount }}" required><br>
        <label for="expCat">Expense category: </label>
        <select name="expenseCategory" id="expCat" required>
            {% for cat in expense_list.0 %}
                <option value="{{ cat.id }}">{{ cat.name }}</option>
            {% endfor %}
        </select><br>
        <input type="hidden" name="expenseID" value="{{ expense_list.1.id }}">
        <label for="expDate">Date paid (YYYY-MM-DD): </label>
        <input type="date" name="expenseDate" id="expDate" value="{{ expense_list.1.date_paid|date:'Y-m-d' }}" pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" required><br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

reports/templates/reports/edit_income.html
{% extends "base.html" %}

{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'reports:submit_edited_income' %}" method="post">
        {% csrf_token %}
        <label for="incName">Name of income (Paycheck, Disablity, Stocks, etc.): </label>
        <input type="text" name="incomeName" id="incName" value="{{ income.name }}"><br>
        <label for"incAmt">Amount: </label>
        <input type="number" name="incomeAmount" id="incAmt" min=1 step="any" value="{{ income.amount }}"><br>
        <input type="hidden" name="incomeID" value="{{ income.id }}">
        <label for="incDate">Date paid: </label>
        <input type="date" name="incomeDate" id="incDate"value="{{ income.date_paid|date:'Y-m-d' }}" pattern="(?:19|20)[0-9]{2}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1[0-9]|2[0-9])|(?:(?!02)(?:0[1-9]|1[0-2])-(?:30))|(?:(?:0[13578]|1[02])-31))" required><br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

reports/templates/reports/index.html
{% extends "base.html" %}

{% block content %}
    <div class="container-fluid">
        <h3>Expenses</h3>
    {% if money_list.0 %}
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered" id="expenseTable">
                    <tr>
                        <th>Date paid</th>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                {% for expense in money_list.0 %}
                    <tr>
                        <td>{{ expense.date_paid|date:"m-d" }}</td>
                        <td>{{ expense.name }}</td>
                        <td>${{ expense.amount }}</td>
                        <td><a href="{% url 'reports:edit_expense' expense.id %}"><i class='fas fa-pencil-alt' style='text-align:right'></i></a></td>
                        <td><a href="{% url 'reports:delete_expense' expense.id %}"><i class='fas fa-minus-circle' style='color:red; text-align:right'></i></a></td>
                    <tr>
                {% endfor %}
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'reports:add_expense' %}" class="btn btn-info" role="button">Add New Expense</a>
                <button class="btn btn-info" type="button" id="cat_breakdown_button">Category Breakdown</button>
            </div>
        </div>

        <!-- The Modal -->
        <div id="myModal" class="modal">
            <span class="close">&times;</span>
            <img class="modal-content" id="img01">
            <div id="caption"></div>
        </div>

    {% else %}
        <p>
            It looks like you haven't added anything yet. Add one? <br>
            <a href="{% url 'reports:add_expense' %}">Add Expense</a> <br>
        </p>
    {% endif %}

    </div><br><br>

    <div class="container-fluid">
        <h3>Income</h3>
    {% if money_list.1 %}
        <div class="row">
            <div class="col-md-6">
                <table class="table table-bordered" id="expenseTable">
                    <tr>
                        <th>Date entered</th>
                        <th>Name</th>
                        <th>Amount</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                {% for income in money_list.1 %}
                    <tr>
                        <td>{{ income.date_paid|date:"m-d" }}</td>
                        <td>{{ income.name }}</td>
                        <td>${{ income.amount }}</td>
                        <td><a href="{% url 'reports:edit_income' income.id %}"><i class='fas fa-pencil-alt' style='text-align:right'></i></a></td>
                        <td><a href="{% url 'reports:delete_income' income.id %}"><i class='fas fa-minus-circle' style='color:red; text-align:right'></i></a></td>
                    <tr>
                {% endfor %}
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-3">
                <a href="{% url 'reports:add_income' %}" class="btn btn-info" role="button">Add New Income</a>
            </div>
        </div>

    {% else %}
        <p>
            It looks like you haven't added anything yet. Add one? <br>
            <a href="{% url 'reports:add_income' %}">Add Income</a> <br>
        </p>
    {% endif %}

    </div>

    {% if money_list.2 %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-2">
                    <br><h4>Net</h4>
                    <p id="netAmt">{{ money_list.2 }}</p>
                </div>
            </div>
        </div>
    {% endif %}

<div class="container-fluid">
    <br><a href="{% url 'reports:add_category' %}" class="btn btn-info" role="button">Add new category</a>
</div>
{% endblock %}